# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/2014104101/Termproj/Termproj.cache/wt [current_project]
set_property parent.project_path D:/2014104101/Termproj/Termproj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths D:/2014104101/ip_repo [current_project]
add_files D:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/2014104101/Termproj/Termproj.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib D:/2014104101/Termproj/Termproj.srcs/sources_1/imports/hdl/system_wrapper.v
read_xdc D:/2014104101/soc_test/test_push/test_push.srcs/constrs_1/imports/digital_clock_files2/top.xdc
set_property used_in_implementation false [get_files D:/2014104101/soc_test/test_push/test_push.srcs/constrs_1/imports/digital_clock_files2/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
